# Generated by Django 5.2.1 on 2025-05-26 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoOnlineApp', '0002_alter_aluno_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='representante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_representada', to='AlunoOnlineApp.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
