# Generated by Django 5.2.1 on 2025-05-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoOnlineApp', '0003_turma_representante_alter_turma_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
