# Generated by Django 5.2.1 on 2025-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoOnlineApp', '0004_aluno_ativo_professor_ativo_turma_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='nome_turma',
            field=models.CharField(max_length=100),
        ),
    ]
