# Generated by Django 5.2.1 on 2025-05-27 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoOnlineApp', '0005_alter_turma_nome_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='nome_turma',
            new_name='serie',
        ),
        migrations.AddField(
            model_name='aluno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
