# Generated by Django 5.2.1 on 2025-06-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoOnlineApp', '0006_rename_nome_turma_turma_serie_aluno_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_aluno',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_aluno/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='foto_professor',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_professores/'),
        ),
    ]
